import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Footer Sections
    work: 'WORK',
    shop: 'SHOP',
    sanatSiteCom: 'SANATSITE.COM',
    order: 'ORDER',
    copyright: '© 2026 SanatSite. All rights reserved.',

    // Art Styles
    digital: 'Digital',
    watercolor: 'Watercolor',
    acrylic: 'Acrylic',
    mixedMedia: 'Mixed Media',
    collage: 'Collage',
    book: 'Book',
    commissioned: 'Commissioned',
    graphicPen: 'Graphic Pen',
    gouache: 'Gouache',
    monotype: 'Monotype',
    sketches: 'Sketches',

    // Categories (Slug-based for cleaner dynamic translation)
    'open-edition-prints': 'Open Edition Prints',
    'photography': 'Photography',
    'digital-art': 'Digital Art',
    'original-works': 'Original Works',

    // Shop Links
    new: 'New',
    prints: 'Prints',
    sets: 'Sets',
    limitedEdition: 'Limited Edition',
    originals: 'Originals',
    books: 'Books',

    // Info Links
    about: 'About',
    printAtelier: 'Print Atelier',
    teamCollaborations: 'Team & Collaborations',
    contact: 'Contact',

    // Order Links
    login: 'Log-in',
    search: 'Search',
    shipment: 'Shipment',
    returnRefund: 'Return & Refund',
    policies: 'Policies',
    faqs: 'F.A.Q.s',

    // Artwork Detail
    home: 'Home',
    noFrame: 'No Frame',
    frame: 'Frame',
    stretchedCanvas: 'Stretched Canvas',
    material: 'Material',
    photographPaper: 'Photograph Paper',
    canvas: 'Canvas',
    signedArchivalPaper: 'Signed Archival Paper',
    size: 'Size',
    freeShipping: 'Free Shipping',
    estimatedShipping: 'Estimated shipping between',
    addToCart: 'Add to Cart',
    addingToCart: 'Adding to Cart...',
    soldOut: 'Sold Out',
    frameLabel: 'Frame',
    materialLabel: 'Material',
    sizeLabel: 'Size',
    mediumLabel: 'Medium:',
    dimensionsLabel: 'Dimensions:',
    yearLabel: 'Year:',
    aboutPiece: 'About this piece',

    // General
    gallery: 'Gallery',
    allArtworks: 'All Artworks',
    galleryHeroTitle: 'Art That Speaks to You',
    galleryHeroSubtitle: 'Discover unique pieces from talented artists. Each work tells a story waiting to be heard.',
    startExploring: 'Start Exploring',
    artworksHeroTitle: 'Curated Collection',
    artworksHeroSubtitle: 'Explore our hand-picked selection of unique artworks from emerging and established artists.',
    artists: 'Artists',
    shoppingCart: 'Shopping Cart',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    myOrders: 'My Orders',
    adminPanel: 'Admin Panel',
    selectCountry: 'Select Country',
    selectCity: 'Select City/Province',
    selectDistrict: 'Select District',
    enterValidCity: 'Please select a valid city',
    enterValidState: 'Please select a valid district',
    enterValidCountry: 'Please select a valid country',
    enterValidZip: 'Please enter a valid postal/zip code',
    artistDashboard: 'Artist Dashboard',
    myPublicProfile: 'My Public Profile',
    total: 'Total',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    proceedToCheckout: 'Proceed to Checkout',
    yourCartIsEmpty: 'Your cart is empty',
    pleaseSignInToViewCart: 'Please sign in to view your cart',
    available: 'Available',
    sold: 'Sold',
    backToCollection: 'Back to Collection',
    aboutThisPiece: 'About this piece',
    medium: 'Medium',
    dimensions: 'Dimensions',
    orientation: 'Orientation',
    horizontal: 'Horizontal',
    vertical: 'Vertical',
    square: 'Square',
    year: 'Year',
    artCollection: 'Welcome to SanatSite',
    browseOurCompleteCollection: 'Browse our complete collection of artworks',
    allCategories: 'All Categories',
    loadingArtworks: 'Loading artworks...',
    noArtworksFound: 'No artworks found',
    discoverTalentedArtists: 'Discover Talented Artists',
    exploreOurCuratedCollection: 'Explore our curated collection of talented artists',
    artworks: 'Artworks',
    artist: 'Artist',
    artistLabel: 'Artist',
    category: 'Category',
    categoryLabel: 'Category',
    selectArtist: 'Select Artist',
    selectCategory: 'Select Category',
    noSubmissionsYet: 'No submissions yet',
    orientationLabel: 'Orientation',
    viewArtist: 'View Artist',
    checkout: 'Checkout',
    completeYourPurchase: 'Complete Your Purchase',
    shippingInformation: 'Shipping Information',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    streetAddress: 'Street Address',
    address: 'Address',
    email: 'Email',
    city: 'City',
    stateLabel: 'State / Province',
    cityLabel: 'City / District',
    stateProvince: 'State/Province',
    state: 'State',
    district: 'District',
    zipPostalCode: 'ZIP/Postal Code',
    zipCode: 'ZIP Code',
    country: 'Country',
    paymentMethod: 'Payment Method',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date (MM/YY)',
    cvv: 'CVV',
    placeOrder: 'Place Order',
    processing: 'Processing...',
    orderSummary: 'Order Summary',
    orderConfirmed: 'Order Confirmed!',
    thankYouForYourPurchase: 'Thank you for your purchase! Your order has been confirmed.',
    orderNumber: 'Order Number',
    orderCompleteTitle: 'Order Complete!',
    orderCompleteMessage: 'Thank you for your purchase. Your artwork will be shipped soon.',
    viewMyOrders: 'View My Orders',
    continueShopping: 'Continue Shopping',
    myOrdersTitle: 'My Orders',
    orderHistory: 'View your order history and track shipments',
    noOrders: "You haven't placed any orders yet",
    startShopping: 'Start Shopping',
    pending: 'Pending',
    processing2: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    language: 'Language',
    currency: 'Currency',
    priceRange: 'Price Range',
    anyPrice: 'Any Price',
    under: 'Under',
    andAbove: 'and Above',
    whereCreativityMeetsInspiration: 'Where Creativity Meets Inspiration',
    welcomeToAWorldOf: 'Welcome to a World of',
    creativeExpression: 'Creative Expression',
    homeDescription: 'Step into our gallery where every piece tells a unique story. Discover the passion, imagination, and talent of artists from around the globe. Let their creativity inspire yours.',
    browseAllArt: 'Browse All Art',
    browseOurCompleteCollectionDesc: 'Step into a world of creativity and inspiration. Explore our unique gallery of original artworks.',
    meetOurArtistsDesc: 'Explore our curated community of talented creators and their unique journeys.',
    loadingGallery: 'Loading gallery...',
    featuredArtwork: 'Featured Artwork',
    shopCategory: 'Shop',
    viewArtwork: 'View Artwork',
    by: 'by',
    back: 'Back',
    filterByArtist: 'Filter by Artist',
    allArtists: 'All Artists',
    allMediums: 'All Mediums',
    filterByCategory: 'Filter by Category',
    all: 'All',
    noArtworksInCategory: 'No artworks found in this category',
    framesDisplayOnly: '*Frames are for display purposes only',
    basePrice: 'Base price',
    digitalPrintOf: 'Digital print of',
    original: 'original',
    format: 'Format',
    stretchedCanvasNote: '* Stretched canvas can only be printed on canvas material',
    largestSizeNote: '* Largest size (96x128cm) not available for stretched canvas',
    variousDimensions: 'various dimensions and printing surfaces',
    createdIn: 'was created in',
    openEditionDescription: 'Open edition print that can be produced in',
    featuredArtists: 'Featured Artists',
    featuredArtistsDesc: 'Meet the visionaries behind our most captivating pieces.',
    latestArtworks: 'Latest Artworks',
    latestArtworksDesc: 'Explore the newest additions to our ever-growing collection.',
    various: 'Various',
    collection: 'Collection',
    signInToCheckout: 'Please sign in to checkout',
    cartEmpty: 'Your cart is empty',
    browseArtworks: 'Browse Artworks',
    backToShopping: 'Back to Shopping',
    completePurchase: 'Complete Purchase',
    signInToViewOrders: 'Please sign in to view orders',
    myOrdersLabel: 'My Orders',
    viewPurchaseHistory: 'View your purchase history',
    noOrdersYet: 'No orders yet',
    orderHash: 'Order #',
    completed: 'Completed',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome Back',
    signInTitle: 'Sign in to your account',
    password: 'Password',
    loading: 'Loading...',
    signUp: 'Sign Up',
    signIn2: 'Sign In', // Changed from signIn to avoid conflict
    alreadyHaveAccount: 'Already have an account? Sign in',
    dontHaveAccount: "Don't have an account? Sign up",

    // Artist Application
    joinCommunity: 'Join Our Artist Community',
    shareArtDescription: 'Share your art with the world. Fill out the application below and we\'ll review your submission.',
    artistApplicationDesc: 'We are always looking for fresh perspectives and inspiring talent to join our curated gallery.',
    firstName: 'First Name',
    lastName: 'Last Name',
    artistType: 'Artist Type',
    selectType: 'Select your type',
    painter: 'Painter',
    photographer: 'Photographer',
    digitalArtist: 'Digital Artist',
    hobbyist: 'Hobbyist',
    portfolioLink: 'Portfolio Link',
    portfolioDescription: 'Link to your online portfolio, Instagram, or website',
    profilePhoto: 'Profile Photo / Headshot',
    uploadFile: 'Upload a file',
    orDragDrop: 'or drag and drop',
    fileLimits: 'PNG, JPG, GIF up to 5MB',
    artistStatement: 'Artist Statement',
    artistStatementPlaceholder: 'Tell us about your artistic journey, style, and what inspires you...',
    submitApplication: 'Submit Application',
    submitting: 'Submitting...',
    uploadingPhoto: 'Uploading Photo...',
    applicationSuccess: 'Application submitted successfully! We will review your application and get back to you soon.',
    photoUploadSuccess: 'Photo uploaded successfully!',
    backToArtists: 'Back to Artists',
    artistNotFound: 'Artist Not Found',
    artistNotFoundDesc: 'The artist you are looking for does not exist or has been removed.',
    meetOurArtists: 'Meet Our Artists',
    joinUsAsArtist: 'Join Us as an Artist',
    edit: 'Edit',
    website: 'Website',
    instagram: 'Instagram',
    artworkCount: 'Artwork',
    artworksCount: 'Artworks',
    discoverTalentedCreators: 'Discover Talented Creators',
    viewProfile: 'View Profile',
    pieceAvailable: 'piece available',
    piecesAvailable: 'pieces available',
    clickToViewDetails: 'Click to view details',
    noArtworksYet: 'No artworks yet',
    unknownArtwork: 'Unknown Artwork',
    unknownArtist: 'Unknown Artist',
    failedToCompleteOrder: 'Failed to complete order',
    switchLanguage: 'Switch to English',
    backToProjects: 'Back to Projects',
    backToDashboard: 'Back to Dashboard',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    discardChanges: 'Discard Changes',
    profileUpdated: 'Profile updated successfully!',
    profileUpdateError: 'Error updating profile. Please try again.',
    profileNotFound: 'Artist Profile Not Found',
    profileNotFoundDesc: "We couldn't find an artist profile linked to your account. If you believe this is an error, please contact support.",
    returnHome: 'Return Home',
    artistDashboardTitle: 'Artist Dashboard',
    customizeProfileDesc: 'Customize your public artist profile',
    viewPublicPage: 'View Public Page',
    profileImageURL: 'Profile Image URL',
    displayName: 'DisplayName',
    biography: 'Biography',
    tellYourStory: 'Tell your story...',
    instagramUsername: 'Instagram Username',
    rates: 'Rates',
    applications: 'Applications',
    manageExchangeRates: 'Manage Exchange Rates',
    exchangeRatesDesc: 'Update exchange rates relative to USD. When you change rates, artworks priced in their original currency will automatically convert to new amounts in other currencies.',
    usdRateLabel: 'USD Rate (Base Currency)',
    eurRateLabel: 'EUR Rate (€)',
    gbpRateLabel: 'GBP Rate (£)',
    tryRateLabel: 'TRY Rate (₺)',
    baseCurrencyDesc: 'Base currency, always 1.0',
    rateConversionDesc: '1 USD = {rate} {currency}',
    saveExchangeRates: 'Save Exchange Rates',
    exchangeRatesUpdated: 'Exchange rates updated successfully!',
    exchangeRatesUpdateError: 'Error updating exchange rates',
    addNewArtwork: 'Add New Artwork',
    editArtwork: 'Edit Artwork',
    title: 'Title',
    price: 'Price',
    baseCurrency: 'Base Currency',
    baseCurrencyLongDesc: 'Currency this artwork is originally priced in',
    imageURL: 'Image URL',
    dimensionsInput: 'Dimensions (e.g., 24x36 inches)',
    yearInput: 'Year (e.g., 2024)',
    mediumInput: 'Medium (e.g., Oil on canvas)',
    description: 'Description',
    updateArtwork: 'Update Artwork',
    createArtwork: 'Create Artwork',
    existingArtworks: 'Existing Artworks',
    deleteArtworkConfirm: 'Are you sure you want to delete this artwork?',
    artworkDeleted: 'Artwork deleted successfully!',
    errorSavingArtwork: 'Error saving artwork',
    manageArtists: 'Manage Artists',
    repairProfileLinks: 'Repair Profile Links',
    repairing: 'Repairing...',
    deleteArtistConfirm: 'Are you sure you want to delete this artist? All their artworks might be affected.',
    artistDeleted: 'Artist deleted successfully!',
    artistApproved: 'Artist approved successfully!',
    errorApprovingArtist: 'Error approving artist',
    errorDeletingArtist: 'Error deleting artist',
    repairSlugsSuccess: 'Updated slugs for {count} artists!',
    repairSlugsError: 'Error fixing slugs',
    artistApplications: 'Artist Applications',
    noPendingApplications: 'No pending applications',
    rejectApplicationConfirm: 'Reject this application?',
    approve: 'Approve',
    error: 'Error',
    success: 'Success',
    switchToTurkish: 'Switch to Turkish',
    switchToEnglish: 'Switch to English',

    // Submission Flow
    submitArtwork: 'Submit New Artwork',
    submissions: 'Submissions',
    pendingSubmissions: 'Pending Submissions',
    approvedSubmissions: 'Approved Submissions',
    uploadArtworkImage: 'Upload Artwork Image',
    createSubmission: 'Send for Review',
    submissionPending: 'Pending Review',
    submissionApproved: 'Approved',
    submissionRejected: 'Rejected',
    submissionSent: 'Submission sent successfully!',
    errorSendingSubmission: 'Error sending submission',
    selectFromApproved: 'Select from Approved Submissions',
    noApprovedSubmissions: 'No approved submissions available',
    selectSubmission: 'Select Submission',
    deleteSubmissionConfirm: 'Delete this submission?',
    submissionDeleted: 'Submission deleted',

    // Customer Dashboard
    customerDashboard: 'Customer Dashboard',
    myProfile: 'My Profile',
    myFavorites: 'My Favorites',
    followedArtists: 'Followed Artists',
    notifications: 'Notifications',
    dashboardOverview: 'Dashboard Overview',
    totalOrders: 'Total Orders',
    totalFavorites: 'Total Favorites',
    artistsFollowing: 'Artists Following',
    unreadNotifications: 'Unread Notifications',
    orderDetails: 'Order Details',
    orderItems: 'Order Items',
    shippingAddress: 'Shipping Address',
    billingAddress: 'Billing Address',
    paymentStatus: 'Payment Status',
    paid: 'Paid',
    failed: 'Failed',
    refunded: 'Refunded',
    viewOrder: 'View Order',
    noFavoritesYet: 'No favorites yet',
    startBrowsing: 'Start Browsing',
    removeFromFavorites: 'Remove from Favorites',
    unfollowArtist: 'Unfollow Artist',
    noFollowedArtists: 'Not following any artists yet',
    markAsRead: 'Mark as Read',
    markAllAsRead: 'Mark All as Read',
    noNotifications: 'No notifications',
    newArtworkFrom: 'New artwork from',
    orderStatusUpdated: 'Order status updated',
    editProfile: 'Edit Profile',
    phoneNumber: 'Phone Number',
    updateProfile: 'Update Profile',
    profileUpdatedSuccess: 'Profile updated successfully!',
    addToFavorites: 'Add to Favorites',
    followArtist: 'Follow Artist',
    following: 'Following',
    cancelled: 'Cancelled',
    since: 'since',
    notProvided: 'Not provided',
    memberSince: 'Member since',
    cancel: 'Cancel',
    viewInRoom: 'View in Room',
    follow: 'Follow',
    pleaseSignIn: 'Please sign in to follow artists',
    followUs: 'Follow Us',

    // Email Verification
    verifyEmailTitle: 'Check Your Email',
    verifyEmailMessage: 'We have sent a verification link to your email address. Please click the link to verify your account.',
    verifyEmailSpamNote: "If you don't see the email, please check your spam folder.",
    resendVerificationEmail: 'Resend Verification Email',
    verificationEmailSent: 'Verification email resent!',
    backToSignIn: 'Back to Sign In',
    verificationSuccessful: 'Verification Successful!',
    verificationSuccessSubtitle: 'Your email has been verified. You can now sign in to your account.',
    redirectingToLogin: 'Redirecting to login page in {seconds} seconds...',
    goToSignIn: 'Go to Sign In',
  },

  tr: {
    // Footer Sections
    work: 'ÇALIŞMALAR',
    shop: 'MAĞAZA',
    sanatSiteCom: 'SANATSITE.COM',
    order: 'SİPARİŞ',
    copyright: '© 2026 SanatSite. Tüm hakları saklıdır.',

    // Art Styles
    digital: 'Dijital',
    watercolor: 'Sulu Boya',
    acrylic: 'Akrilik',
    mixedMedia: 'Karışık Teknik',
    collage: 'Kolaj',
    book: 'Kitap',
    commissioned: 'Özel Sipariş',
    graphicPen: 'Grafik Kalemi',
    gouache: 'Guaj',
    monotype: 'Monotip',
    sketches: 'Eskizler',

    // Categories (Slug-based)
    'open-edition-prints': 'Açık Edisyon Baskılar',
    'photography': 'Fotoğraflar',
    'digital-art': 'Dijital Art',
    'original-works': 'Orijinal Eserler',

    // Shop Links
    new: 'Yeni',
    prints: 'Baskılar',
    sets: 'Setler',
    limitedEdition: 'Sınırlı Baskı',
    originals: 'Orijinaller',
    books: 'Kitaplar',

    // Info Links
    about: 'Hakkında',
    printAtelier: 'Baskı Atölyesi',
    teamCollaborations: 'Ekip & İşbirlikleri',
    contact: 'İletişim',

    // Order Links
    login: 'Giriş Yap',
    search: 'Ara',
    shipment: 'Teslimat',
    returnRefund: 'İade & Geri Ödeme',
    policies: 'Politikalar',
    faqs: 'S.S.S.',

    // Artwork Detail
    home: 'Anasayfa',
    noFrame: 'Çerçevesiz',
    frame: 'Çerçeveli',
    stretchedCanvas: 'Gerdirilmiş Kanvas',
    material: 'Materyal',
    photographPaper: 'Fotoğraf Kağıdı',
    canvas: 'Kanvas',
    signedArchivalPaper: 'İmzalı Arşiv Kağıdı',
    size: 'Boyut',
    freeShipping: 'Ücretsiz Kargo',
    estimatedShipping: 'Tahmini teslimat:',
    addToCart: 'Sepete Ekle',
    addingToCart: 'Sepete Ekleniyor...',
    soldOut: 'Tükendi',
    frameLabel: 'Çerçeve',
    materialLabel: 'Materyal',
    sizeLabel: 'Boyut',
    mediumLabel: 'Teknik:',
    dimensionsLabel: 'Boyutlar:',
    yearLabel: 'Yıl:',
    aboutPiece: 'Bu eser hakkında',

    // General
    gallery: 'Galeri',
    allArtworks: 'Tüm Eserler',
    galleryHeroTitle: 'Size Hitap Eden Sanat',
    galleryHeroSubtitle: 'Yetenekli sanatçıların eşsiz eserlerini keşfedin. Her eser, duyulmayı bekleyen bir hikaye anlatıyor.',
    startExploring: 'Keşfetmeye Başla',
    artworksHeroTitle: 'Özenle Seçilmiş Koleksiyon',
    artworksHeroSubtitle: 'Yükselen ve yerleşik sanatçıların eşsiz eserlerinden oluşan seçkimizi keşfedin.',
    artists: 'Sanatçılar',
    shoppingCart: 'Alışveriş Sepeti',
    signIn: 'Giriş Yap',
    signOut: 'Çıkış Yap',
    myOrders: 'Siparişlerim',
    adminPanel: 'Yönetim Paneli',
    selectCountry: 'Ülke Seçiniz',
    selectCity: 'İl Seçiniz',
    selectDistrict: 'İlçe Seçiniz',
    district: 'İlçe',
    enterValidCity: 'Lütfen geçerli bir il seçiniz',
    enterValidState: 'Lütfen geçerli bir ilçe seçiniz',
    enterValidCountry: 'Lütfen geçerli bir ülke seçiniz',
    enterValidZip: 'Lütfen geçerli bir posta kodu giriniz',
    artistDashboard: 'Sanatçı Paneli',
    myPublicProfile: 'Genel Profilim',
    total: 'Toplam',
    subtotal: 'Ara Toplam',
    shipping: 'Kargo',
    free: 'Ücretsiz',
    proceedToCheckout: 'Ödemeye Geç',
    yourCartIsEmpty: 'Sepetiniz boş',
    pleaseSignInToViewCart: 'Sepetinizi görüntülemek için lütfen giriş yapın',
    available: 'Mevcut',
    sold: 'Satıldı',
    backToCollection: 'Koleksiyona Dön',
    aboutThisPiece: 'Bu eser hakkında',
    medium: 'Teknik',
    dimensions: 'Boyutlar',
    orientation: 'Yön',
    horizontal: 'Yatay',
    vertical: 'Dikey',
    square: 'Kare',
    year: 'Yıl',
    artCollection: 'SanatSite\'a Hoş Geldiniz',
    browseOurCompleteCollection: 'Tam koleksiyonumuza göz atın',
    allCategories: 'Tüm Kategoriler',
    loadingArtworks: 'Eserler yükleniyor...',
    noArtworksFound: 'Eser bulunamadı',
    discoverTalentedArtists: 'Yetenekli Sanatçıları Keşfedin',
    exploreOurCuratedCollection: 'Özenle seçilmiş sanatçı koleksiyonumuzu keşfedin',
    artworks: 'Eserler',
    artist: 'Sanatçı',
    artistLabel: 'Sanatçı',
    category: 'Kategori',
    categoryLabel: 'Kategori',
    selectArtist: 'Sanatçı Seçiniz',
    selectCategory: 'Kategori Seçiniz',
    noSubmissionsYet: 'Henüz gönderi yok',
    orientationLabel: 'Yön',
    viewArtist: 'Sanatçıyı Görüntüle',
    checkout: 'Ödeme',
    completeYourPurchase: 'Alışverişinizi Tamamlayın',
    shippingInformation: 'Teslimat Bilgileri',
    fullName: 'Ad Soyad',
    emailAddress: 'E-posta Adresi',
    streetAddress: 'Sokak Adresi',
    address: 'Adres',
    email: 'E-posta',
    stateLabel: 'İl',
    cityLabel: 'İlçe',
    city: 'İlçe',
    stateProvince: 'İl',
    state: 'İl',
    zipPostalCode: 'Posta Kodu',
    zipCode: 'Posta Kodu',
    country: 'Ülke',
    paymentMethod: 'Ödeme Yöntemi',
    cardNumber: 'Kart Numarası',
    expiryDate: 'Son Kullanma Tarihi (AA/YY)',
    cvv: 'CVV',
    placeOrder: 'Siparişi Tamamla',
    processing: 'İşleniyor...',
    orderSummary: 'Sipariş Özeti',
    orderConfirmed: 'Sipariş Onaylandı!',
    thankYouForYourPurchase: 'Alışverişiniz için teşekkür ederiz! Siparişiniz onaylandı.',
    orderNumber: 'Sipariş Numarası',
    orderCompleteTitle: 'Sipariş Tamamlandı!',
    orderCompleteMessage: 'Satın aldığınız için teşekkür ederiz. Eseriniz yakında kargoya verilecektir.',
    viewMyOrders: 'Siparişlerimi Görüntüle',
    continueShopping: 'Alışverişe Devam Et',
    myOrdersTitle: 'Siparişlerim',
    orderHistory: 'Sipariş geçmişinizi görüntüleyin ve gönderileri takip edin',
    noOrders: 'Henüz sipariş vermediniz',
    startShopping: 'Alışverişe Başla',
    pending: 'Beklemede',
    processing2: 'İşleniyor',
    shipped: 'Kargoda',
    delivered: 'Teslim Edildi',
    language: 'Dil',
    currency: 'Para Birimi',
    priceRange: 'Fiyat Aralığı',
    anyPrice: 'Tüm Fiyatlar',
    under: 'Altı',
    andAbove: 've Üzeri',
    whereCreativityMeetsInspiration: 'Yaratıcılığın İlhamla Buluştuğu Yer',
    welcomeToAWorldOf: 'Bir Dünyaya Hoş Geldiniz',
    creativeExpression: 'Yaratıcı İfade',
    homeDescription: 'Her eserin benzersiz bir hikaye anlattığı galerimize adım atın. Dünyanın dört bir yanındaki sanatçıların tutkusunu, hayal gücünü ve yeteneğini keşfedin. Yaratıcılıkları size ilham versin.',
    browseAllArt: 'Tüm Sanat Eserlerine Göz Atın',
    meetTheArtists: 'Sanatçılarla Tanışın',
    loadingGallery: 'Galeri yükleniyor...',
    featuredArtwork: 'Öne Çıkan Eser',
    shopCategory: 'Alışveriş Yap',
    viewArtwork: 'Eseri Görüntüle',
    by: 'tarafından',
    back: 'Geri',
    filterByArtist: 'Sanatçıya Göre Filtrele',
    allArtists: 'Tüm Sanatçılar',
    allMediums: 'Tüm Teknikler',
    filterByCategory: 'Kategoriye Göre Filtrele',
    all: 'Hepsi',
    noArtworksInCategory: 'Bu kategoride eser bulunamadı',
    framesDisplayOnly: '*Çerçeveler sadece görsel amaçlıdır',
    basePrice: 'Liste fiyatı',
    digitalPrintOf: 'Dijital baskı:',
    original: 'orijinal',
    format: 'Format',
    stretchedCanvasNote: '* Şaseli tuval sadece tuval materyali üzerine basılabilir',
    largestSizeNote: '* En büyük boyut (96x128cm) şaseli tuval için mevcut değildir',
    variousDimensions: 'çeşitli boyutlarda ve baskı yüzeylerinde',
    createdIn: 'yılında üretilmiştir',
    openEditionDescription: 'Açık edisyon baskı olup, farklı boyut ve yüzeylerde üretilebilir',
    various: 'Çeşitli',
    collection: 'Koleksiyon',
    signInToCheckout: 'Ödeme yapmak için lütfen giriş yapın',
    cartEmpty: 'Sepetiniz boş',
    browseArtworks: 'Eserlere Göz At',
    backToShopping: 'Alışverişe Geri Dön',
    completePurchase: 'Alışverişi Tamamla',
    signInToViewOrders: 'Siparişleri görüntülemek için lütfen giriş yapın',
    myOrdersLabel: 'Siparişlerim',
    viewPurchaseHistory: 'Satın alma geçmişinizi görüntüleyin',
    noOrdersYet: 'Henüz siparişiniz yok',
    orderHash: 'Sipariş #',
    completed: 'Tamamlandı',
    createAccount: 'Hesap Oluştur',
    welcomeBack: 'Tekrar Hoş Geldiniz',
    signInTitle: 'Hesabınıza giriş yapın',
    password: 'Şifre',
    loading: 'Yükleniyor...',
    signUp: 'Kayıt Ol',
    signIn2: 'Giriş Yap',
    alreadyHaveAccount: 'Zaten bir hesabınız var mı? Giriş yapın',
    dontHaveAccount: 'Hesabınız yok mu? Kayıt olun',

    // Artist Application
    joinCommunity: 'Sanatçı Topluluğumuza Katılın',
    shareArtDescription: 'Sanatınızı dünyayla paylaşın. Aşağıdaki başvuru formunu doldurun, başvurunuzu inceleyelim.',
    firstName: 'Ad',
    lastName: 'Soyad',
    artistType: 'Sanatçı Tipi',
    selectType: 'Tip seçiniz',
    painter: 'Ressam',
    photographer: 'Fotoğrafçı',
    digitalArtist: 'Dijital Sanatçı',
    hobbyist: 'Hobi Sanatçısı',
    portfolioLink: 'Portfolyo Bağlantısı',
    portfolioDescription: 'Online portfolyonuz, Instagram veya web sitenizin bağlantısı',
    profilePhoto: 'Profil Fotoğrafı / Vesikalık',
    uploadFile: 'Dosya yükle',
    orDragDrop: 'veya sürükleyip bırakın',
    fileLimits: 'PNG, JPG, GIF (maks. 5MB)',
    artistStatement: 'Sanatçı Özgeçmişi / İfadesi',
    artistStatementPlaceholder: 'Sanatsal yolculuğunuz, tarzınız ve size neyin ilham verdiği hakkında bilgi verin...',
    submitApplication: 'Başvuruyu Gönder',
    submitting: 'Gönderiliyor...',
    uploadingPhoto: 'Fotoğraf Yükleniyor...',
    applicationSuccess: 'Başvurunuz başarıyla gönderildi! Başvurunuzu inceleyip en kısa sürede size döneceğiz.',
    photoUploadSuccess: 'Fotoğraf başarıyla yüklendi!',
    backToArtists: 'Sanatçılara Dön',
    artistNotFound: 'Sanatçı Bulunamadı',
    artistNotFoundDesc: 'Aradığınız sanatçı mevcut değil veya kaldırılmış olabilir.',
    featuredArtists: 'Öne Çıkan Sanatçılar',
    featuredArtistsDesc: 'En büyüleyici eserlerimizin arkasındaki vizyonerlerle tanışın.',
    latestArtworks: 'Son Eklenen Eserler',
    latestArtworksDesc: 'Sürekli büyüyen koleksiyonumuza yeni eklenenleri keşfedin.',
    meetOurArtists: 'Sanatçılarımızla Tanışın',
    meetOurArtistsDesc: 'Küratörlüğünü yaptığımız yetenekli topluluğumuzu ve benzersiz hikayelerini keşfedin.',
    browseOurCompleteCollectionDesc: 'Yaratıcılık ve ilham dünyasına adım atın. Orijinal sanat eserlerinden oluşan benzersiz galerimizi keşfedin.',
    joinUsAsArtist: 'Bize Katılın',
    artistApplicationDesc: 'Küratörlüğünü yaptığımız galerimize katılacak taze bakış açıları ve ilham verici yetenekler arıyoruz.',
    edit: 'Düzenle',
    website: 'Web Sitesi',
    instagram: 'Instagram',
    artworkCount: 'Eser',
    artworksCount: 'Eser',
    discoverTalentedCreators: 'Yetenekli Yaratıcıları Keşfedin',
    viewProfile: 'Profili Görüntüle',
    pieceAvailable: 'eser mevcut',
    piecesAvailable: 'eser mevcut',
    clickToViewDetails: 'Detayları görmek için tıklayın',
    noArtworksYet: 'Henüz eser yok',
    unknownArtwork: 'Bilinmeyen Eser',
    unknownArtist: 'Bilinmeyen Sanatçı',
    failedToCompleteOrder: 'Sipariş tamamlanamadı',
    switchLanguage: 'Türkçe\'ye geç',
    backToProjects: 'Projelere Dön',
    backToDashboard: 'Panele Dön',
    saveChanges: 'Değişiklikleri Kaydet',
    saving: 'Kaydediliyor...',
    discardChanges: 'Değişiklikleri Geri Al',
    profileUpdated: 'Profil başarıyla güncellendi!',
    profileUpdateError: 'Profil güncellenirken hata oluştu. Lütfen tekrar deneyin.',
    profileNotFound: 'Sanatçı Profili Bulunamadı',
    profileNotFoundDesc: 'Hesabınızla bağlantılı bir sanatçı profili bulamadık. Bunun bir hata olduğunu düşünüyorsanız lütfen destekle iletişime geçin.',
    returnHome: 'Anasayfaya Dön',
    artistDashboardTitle: 'Sanatçı Paneli',
    customizeProfileDesc: 'Genel sanatçı profilinizi özelleştirin',
    viewPublicPage: 'Genel Profili Görüntüle',
    profileImageURL: 'Profil Resmi URL\'si',
    displayName: 'Görünen Ad',
    biography: 'Biyografi',
    tellYourStory: 'Hikayenizi anlatın...',
    instagramUsername: 'Instagram Kullanıcı Adı',
    rates: 'Kurlar',
    applications: 'Başvurular',
    manageExchangeRates: 'Döviz Kurlarını Yönet',
    exchangeRatesDesc: 'Döviz kurlarını USD bazlı olarak güncelleyin. Kurları değiştirdiğinizde, orijinal para birimiyle fiyatlandırılan eserlerin diğer para birimlerindeki karşılıkları otomatik olarak güncellenecektir.',
    usdRateLabel: 'USD Kuru (Ana Para Birimi)',
    eurRateLabel: 'EUR Kuru (€)',
    gbpRateLabel: 'GBP Kuru (£)',
    tryRateLabel: 'TRY Kuru (₺)',
    baseCurrencyDesc: 'Ana para birimi, her zaman 1.0',
    rateConversionDesc: '1 USD = {rate} {currency}',
    saveExchangeRates: 'Kurları Kaydet',
    exchangeRatesUpdated: 'Döviz kurları başarıyla güncellendi!',
    exchangeRatesUpdateError: 'Döviz kurları güncellenirken hata oluştu',
    addNewArtwork: 'Yeni Eser Ekle',
    editArtwork: 'Eseri Düzenle',
    title: 'Başlık',
    price: 'Fiyat',
    baseCurrency: 'Ana Para Birimi',
    baseCurrencyLongDesc: 'Eserin orijinal olarak fiyatlandırıldığı para birimi',
    imageURL: 'Görsel URL\'si',
    dimensionsInput: 'Boyutlar (örn. 24x36 inç)',
    yearInput: 'Yıl (örn. 2024)',
    mediumInput: 'Teknik (örn. Tuval üzerine yağlıboya)',
    description: 'Açıklama',
    updateArtwork: 'Eseri Güncelle',
    createArtwork: 'Eser Oluştur',
    existingArtworks: 'Mevcut Eserler',
    deleteArtworkConfirm: 'Bu eseri silmek istediğinizden emin misiniz?',
    artworkDeleted: 'Eser başarıyla silindi!',
    errorSavingArtwork: 'Eser kaydedilirken hata oluştu',
    manageArtists: 'Sanatçıları Yönet',
    repairProfileLinks: 'Profil Bağlantılarını Onar',
    repairing: 'Onarılıyor...',
    deleteArtistConfirm: 'Bu sanatçıyı silmek istediğinizden emin misiniz? Tüm eserleri bundan etkilenebilir.',
    artistDeleted: 'Sanatçı başarıyla silindi!',
    artistApproved: 'Sanatçı başarıyla onaylandı!',
    errorApprovingArtist: 'Sanatçı onaylanırken hata oluştu',
    errorDeletingArtist: 'Sanatçı silinirken hata oluştu',
    repairSlugsSuccess: '{count} sanatçının bağlantısı güncellendi!',
    repairSlugsError: 'Bağlantılar onarılırken hata oluştu',
    artistApplications: 'Sanatçı Başvuruları',
    noPendingApplications: 'Bekleyen başvuru yok',
    rejectApplicationConfirm: 'Bu başvuruyu reddetmek istiyor musunuz?',
    approve: 'Onayla',
    reject: 'Reddet',
    error: 'Hata',
    success: 'Başarılı',
    switchToTurkish: 'Türkçe\'ye Geç',
    switchToEnglish: 'İngilizce\'ye Geç',

    // Submission Flow
    submitArtwork: 'Yeni Eser Gönder',
    submissions: 'Gönderiler',
    pendingSubmissions: 'Bekleyen Gönderiler',
    approvedSubmissions: 'Onaylanan Gönderiler',
    uploadArtworkImage: 'Eser Görseli Yükle',
    createSubmission: 'İncelemeye Gönder',
    submissionPending: 'İnceleme Bekliyor',
    submissionApproved: 'Onaylandı',
    submissionRejected: 'Reddedildi',
    submissionSent: 'Gönderi başarıyla iletildi!',
    errorSendingSubmission: 'Gönderi iletilirken hata oluştu',
    selectFromApproved: 'Onaylı Gönderilerden Seç',
    noApprovedSubmissions: 'Onaylı gönderi yok',
    selectSubmission: 'Gönderiyi Seç',
    deleteSubmissionConfirm: 'Bu gönderiyi silmek istiyor musunuz?',
    submissionDeleted: 'Gönderi silindi',

    // Customer Dashboard
    customerDashboard: 'Müşteri Paneli',
    myProfile: 'Profilim',
    myFavorites: 'Favorilerim',
    followedArtists: 'Takip Ettiğim Sanatçılar',
    notifications: 'Bildirimler',
    dashboardOverview: 'Panel Özeti',
    totalOrders: 'Toplam Sipariş',
    totalFavorites: 'Toplam Favori',
    artistsFollowing: 'Takip Edilen Sanatçı',
    unreadNotifications: 'Okunmamış Bildirim',
    orderDetails: 'Sipariş Detayları',
    orderItems: 'Sipariş Ürünleri',
    shippingAddress: 'Teslimat Adresi',
    billingAddress: 'Fatura Adresi',
    paymentStatus: 'Ödeme Durumu',
    paid: 'Ödendi',
    failed: 'Başarısız',
    refunded: 'İade Edildi',
    viewOrder: 'Siparişi Görüntüle',
    noFavoritesYet: 'Henüz favori yok',
    startBrowsing: 'Gezinmeye Başla',
    removeFromFavorites: 'Favorilerden Kaldır',
    unfollowArtist: 'Takibi Bırak',
    noFollowedArtists: 'Henüz takip edilen sanatçı yok',
    markAsRead: 'Okundu Olarak İşaretle',
    markAllAsRead: 'Tümünü Okundu İşaretle',
    noNotifications: 'Bildirim yok',
    newArtworkFrom: 'Yeni eser:',
    orderStatusUpdated: 'Sipariş durumu güncellendi',
    editProfile: 'Profili Düzenle',
    phoneNumber: 'Telefon Numarası',
    updateProfile: 'Profili Güncelle',
    profileUpdatedSuccess: 'Profil başarıyla güncellendi!',
    addToFavorites: 'Favorilere Ekle',
    followArtist: 'Takip Et',
    following: 'Takip Ediliyor',
    cancelled: 'İptal Edildi',
    since: 'tarihinden beri',
    notProvided: 'Belirtilmedi',
    memberSince: 'Üyelik tarihi',
    cancel: 'İptal',
    viewInRoom: 'Odada Görüntüle',
    follow: 'Takip Et',
    pleaseSignIn: 'Sanatçıları takip etmek için lütfen giriş yapın',
    followUs: 'Bizi Takip Edin',

    // Email Verification
    verifyEmailTitle: 'E-postanızı Kontrol Edin',
    verifyEmailMessage: 'E-posta adresinize bir doğrulama bağlantısı gönderdik. Hesabınızı doğrulamak için lütfen bağlantıya tıklayın.',
    verifyEmailSpamNote: 'E-postayı görmüyorsanız, lütfen spam klasörünüzü kontrol edin.',
    resendVerificationEmail: 'Doğrulama E-postasını Tekrar Gönder',
    verificationEmailSent: 'Doğrulama e-postası tekrar gönderildi!',
    backToSignIn: 'Giriş Yap Sayfasına Dön',
    verificationSuccessful: 'Doğrulama Başarılı!',
    verificationSuccessSubtitle: 'E-posta adresiniz doğrulandı. Artık hesabınıza giriş yapabilirsiniz.',
    redirectingToLogin: '{seconds} saniye içinde giriş sayfasına yönlendiriliyorsunuz...',
    goToSignIn: 'Giriş Yap Sayfasına Git',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
